### ISSUE TITLE
Vehicle flying and flipping issues

### ISSUE THREAD

**Issue by ChickenDipper1** [Renewed-Scripts/Renewed-Weaponscarry#10]
Sometimes when having items on back getting in a vehicle will cause it to go crazy and flip around till you get out.

**Comment by ChickenDipper1** [comment]
To resolve this make sure to use the export to remove props when entering a vehicle.

**Comment by eygi** [comment]
> To resolve this make sure to use the export to remove props when entering a vehicle.

where did you put that line

**Comment by ChickenDipper1** [comment]
Make a thread that will check every 1000ms if a player is entering a vehicle, then add the export.

**Comment by GrybasTV** [comment]
> Make a thread that will check every 1000ms if a player is entering a vehicle, then add the export.

Can you show please where you put code exactly in your case?
