### ISSUE TITLE
Weapons visible in noclip for other players when moving into their culling range

### ISSUE THREAD

**Issue by jellyton69** [Renewed-Scripts/Renewed-Weaponscarry#14]
**Tested using txAdmin's noclip on OneSync**

When you move in noclip starting outside of a player's culling range and then move into their culling range your weapons will spawn and attach to your ped in noclip for that client.

**Comment by FjamZoo** [comment]
> When you move in noclip starting outside of a player's culling range and then move into their culling range your weapons will spawn and attach to your ped in noclip for that client.

You need to use the statebag to disable syncing for your player when entering noclip
